name: Teste de Senha

on:
  push:
    branches:
      - main

jobs:
  teste-senha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar Teste de Senha
      run: python script_de_teste.py
